#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

if ARGV.include?('install')

  `git clone https://github.com/atomecorp/opal-browser.git`
  Dir.chdir('opal-browser') do
    `bundle update; bundle install`
    `gem build opal-browser.gemspec`
    `gem install opal-browser`
  end
  `git clone https://github.com/atomecorp/atome.git `

  Dir.chdir('atome/test/test_app/build/') do
    Dir.mkdir('js')

    Dir.chdir('js/') do
      FileUtils.copy_entry('../../../../vendor/assets/build/js/third_parties/', 'third_parties/')
    end
  end
  Dir.chdir('../../../../') do
    `bundle update; bundle install`
    `gem build atome.gemspec`
    `gem install atome`
  end
  # end
  if ARGV.include?('run')
    Dir.chdir('atome/') do
      `rake test`
    end
  end
end
